import { G, R, RS, clamp, lerp, TAU, D2R, hash } from '../core/math';
import { EZ } from '../core/easing';
import { rng, sel, bool, col, DIRS, DIR4, PIV, dv, pivot, CHARSETS, rChar } from './params';
import { fall, floorD, pieces } from './physics';
import { scrHook, fontHook, flapHook, rainHook, cntHook, blkHook } from './hooks';
import type { EffectDef, ParamDef } from './types';
import { pathOffset, pathAngle } from './paths';
import type { PathShape } from './paths';

export const FX: EffectDef[]=[
/* --- Movimento --- */
{id:'slide',n:'Scorrimento',c:'Movimento',d:'Entra scorrendo da una direzione, con o senza dissolvenza.',rec:{split:'char',stagger:.45,ease:'outExpo'},
 p:[sel('dir','Provenienza',DIRS,'B'),rng('dist','Distanza',0,6,.7,.01,'em'),bool('fade','Dissolvenza',true)],
 f(s,p,u,o){const q=1-p,[x,y]=dv(o.dir,u);s.x+=x*o.dist*G.E*q;s.y+=y*o.dist*G.E*q;if(o.fade)s.op*=clamp(p)}},
{id:'traverse',n:'Attraversamento',c:'Movimento',d:'Arriva da fuori dal fotogramma, anche in diagonale. In uscita scegli il lato opposto per farlo attraversare tutto.',rec:{split:'word',stagger:.12,ease:'inOutExpo'},
 p:[sel('dir','Provenienza',DIRS.slice(0,8),'L'),rng('m','Margine extra',0,4,.2,.01,'em'),bool('fade','Dissolvenza',false)],
 f(s,p,u,o){const q=1-p,m=o.m*G.E,d=o.dir;let x=0,y=0;if(d.includes('L'))x=-(u.fx+u.w/2+m);if(d.includes('R'))x=G.W-u.fx+u.w/2+m;if(d.includes('T'))y=-(u.fy+u.by1+m);if(d.includes('B'))y=G.H-u.fy-u.by0+m;s.x+=x*q;s.y+=y*q;if(o.fade)s.op*=clamp(p)}},
{id:'fade',n:'Dissolvenza',c:'Movimento',d:'Dissolvenza pulita, con una leggera deriva opzionale.',rec:{split:'word',stagger:.3,ease:'outCubic'},
 p:[sel('dir','Deriva da',DIRS,'B'),rng('dist','Deriva',0,2,.12,.01,'em')],
 f(s,p,u,o){const q=1-p,[x,y]=dv(o.dir,u);s.x+=x*o.dist*G.E*q;s.y+=y*o.dist*G.E*q;s.op*=clamp(p)}},
{id:'skew',n:'Inclinazione',c:'Movimento',d:'Scivola con i caratteri inclinati che si raddrizzano all\'arrivo.',rec:{split:'char',stagger:.35,ease:'outQuart'},
 p:[sel('dir','Provenienza',[['L','Da sinistra'],['R','Da destra']],'L'),rng('dist','Distanza',0,6,1.4,.01,'em'),rng('ang','Inclinazione',-70,70,-32,1,'°'),bool('fade','Dissolvenza',true)],
 f(s,p,u,o){const q=1-p,v=o.dir==='L'?-1:1;s.x+=v*o.dist*G.E*q;s.skx+=o.ang*q*-v;if(o.fade)s.op*=clamp(p)}},
{id:'drop',n:'Caduta',c:'Movimento',d:'Cade con rimbalzo e una piccola rotazione casuale.',rec:{split:'char',stagger:.5,ease:'outBounce'},
 p:[sel('from','Da',[['T','Dall\'alto'],['B','Dal basso']],'T'),rng('h','Altezza',0,12,2.6,.01,'em'),rng('rot','Rotazione',0,90,10,1,'°')],
 f(s,p,u,o){const q=1-p;s.y+=(o.from==='T'?-1:1)*o.h*G.E*q;s.rot+=RS(u,7)*o.rot*q;s.op*=clamp(p*6)}},
{id:'wavein',n:'Onda d\'ingresso',c:'Movimento',d:'I caratteri arrivano seguendo una sinusoide.',rec:{split:'char',stagger:.55,ease:'outCubic'},
 p:[rng('amp','Ampiezza',0,4,.8,.01,'em'),rng('freq','Frequenza',0,2,.55,.01),rng('cyc','Cicli',0,4,1,.05),bool('fade','Dissolvenza',true)],
 f(s,p,u,o){const q=1-p;s.y+=Math.sin(u.i*o.freq+q*Math.PI*o.cyc*2)*o.amp*G.E*q;s.x+=0;if(o.fade)s.op*=clamp(p)}},
{id:'track',n:'Spaziatura',c:'Movimento',d:'Le lettere si stringono o si allargano fino alla spaziatura finale.',rec:{split:'char',stagger:0,ease:'outExpo'},
 p:[rng('spread','Apertura',-1,6,1.6,.01,'×'),bool('fade','Dissolvenza',true),rng('blur','Sfocatura',0,40,0,1,'px')],
 f(s,p,u,o){const q=1-p;s.x+=u.cx*o.spread*q;if(o.fade)s.op*=clamp(p);s.blur+=o.blur*q}},
/* --- Maschere --- */
{id:'mask',n:'Maschera',c:'Maschere',d:'Il testo sale da dietro una linea invisibile. Il classico dei titoli puliti.',rec:{split:'char',stagger:.35,ease:'outQuart'},
 p:[sel('dir','Provenienza',DIR4,'B'),rng('skew','Inclinazione',-40,40,0,1,'°'),rng('rot','Rotazione',-40,40,0,1,'°')],
 f(s,p,u,o){const q=1-p;s.clip=1;const hh=(u.by1-u.by0)*1.02;switch(o.dir){case'B':s.y+=hh*q;break;case'T':s.y-=hh*q;break;case'L':s.x-=(u.w+G.E*.1)*q;break;default:s.x+=(u.w+G.E*.1)*q}s.skx+=o.skew*q;s.rot+=o.rot*q;if(o.rot)pivot(s,'B',u)}},
{id:'wipe',n:'Rivelazione',c:'Maschere',d:'Una tendina scopre il testo senza muoverlo.',rec:{split:'word',stagger:.3,ease:'inOutQuart'},
 p:[sel('dir','Direzione',[['L','Da sinistra'],['R','Da destra'],['T','Dall\'alto'],['B','Dal basso'],['C','Dal centro']],'L'),rng('edge','Bordo morbido',0,1,0,.01)],
 f(s,p,u,o){s.wipe={d:o.dir,a:clamp(p),soft:o.edge}}},
{id:'split',n:'Taglio a metà',c:'Maschere',d:'Metà superiore e inferiore arrivano da lati opposti e si ricompongono.',rec:{split:'word',stagger:.25,ease:'outExpo'},
 p:[rng('dist','Distanza',0,8,1.4,.01,'em'),bool('fade','Dissolvenza',true),bool('flip','Inverti lati',false)],
 f(s,p,u,o){const q=1-p,d=o.dist*G.E*q*(o.flip?-1:1);s.slices={n:2,off:j=>j?d:-d};if(o.fade)s.op*=clamp(p)}},
{id:'slices',n:'Fette',c:'Maschere',d:'Il testo è tagliato in fette orizzontali che scivolano al loro posto.',rec:{split:'word',stagger:.25,ease:'outQuart'},
 p:[rng('n','Numero fette',2,20,6,1),rng('dist','Distanza',0,8,1.2,.01,'em'),sel('mode','Modalità',[['alt','Alternate'],['rnd','Casuali'],['cas','A cascata']],'alt'),bool('fade','Dissolvenza',true)],
 f(s,p,u,o){const q=1-p,d=o.dist*G.E,n=Math.round(o.n);s.slices={n,off:j=>o.mode==='alt'?(j%2?1:-1)*d*q:o.mode==='rnd'?RS(u,50+j)*d*q:-d*EZ.outCubic(clamp(q*1.6-(j/n)*.6))};if(o.fade)s.op*=clamp(p*1.4)}},
{id:'slot',n:'Rullo slot',c:'Maschere',d:'Ogni carattere gira come un rullo di slot machine prima di fermarsi.',rec:{split:'char',stagger:.35,ease:'outCubic'},
 p:[rng('spins','Giri',1,30,7,1),sel('dir','Verso',[['U','Verso l\'alto'],['D','Verso il basso']],'U'),sel('set','Caratteri',[['AZ','Lettere'],['n09','Numeri'],['sym','Simboli']],'AZ')],
 f(s,p,u,o){s.clip=1;const r=clamp(1-p,0,1)*o.spins,k=Math.floor(r);s.roll={k,frac:r-k,dir:o.dir==='U'?1:-1,set:o.set};s.op*=p>0?1:0}},
{id:'marker',n:'Evidenziatore',c:'Maschere',d:'Una barra piena copre la parola e, ritirandosi, lascia il testo.',rec:{split:'word',stagger:.25,ease:'inOutQuart'},
 p:[sel('dir','Direzione',[['L','Da sinistra'],['R','Da destra'],['T','Dall\'alto'],['B','Dal basso']],'L'),sel('bc','Colore barra',[['B','Colore B'],['A','Colore testo']],'B'),rng('pad','Margine',0,.4,.06,.01,'em')],
 f(s,p,u,o){const a=clamp(p);s.bar={d:o.dir,a:a<.5?0:(a-.5)*2,b:a<.5?a*2:1,c:o.bc,pad:o.pad};s.op*=a>=.5?1:0}},
/* --- Scala e rotazione --- */
{id:'pop',n:'Pop',c:'Scala e rotazione',d:'Cresce da zero con un leggero rimbalzo.',rec:{split:'char',stagger:.45,ease:'outBack'},
 p:[rng('from','Scala iniziale',0,1,0,.01),rng('rot','Rotazione casuale',0,90,0,1,'°'),sel('piv','Perno',PIV,'C')],
 f(s,p,u,o){const k=lerp(o.from,1,p);s.sx*=k;s.sy*=k;s.rot+=RS(u,8)*o.rot*(1-p);pivot(s,o.piv,u);s.op*=clamp(p*4)}},
{id:'zoom',n:'Zoom dall\'alto',c:'Scala e rotazione',d:'Arriva grande e sfocato verso la camera, poi si posa.',rec:{split:'word',stagger:.25,ease:'outExpo'},
 p:[rng('from','Scala iniziale',1,10,3,.01,'×'),rng('blur','Sfocatura',0,60,14,1,'px'),bool('fade','Dissolvenza',true)],
 f(s,p,u,o){const q=1-p,k=lerp(o.from,1,p);s.sx*=k;s.sy*=k;s.blur+=o.blur*q;if(o.fade)s.op*=clamp(p)}},
{id:'depth',n:'Profondità',c:'Scala e rotazione',d:'Emerge dalla profondità o arriva dal primo piano, con sfocatura di campo.',rec:{split:'char',stagger:.4,ease:'outQuart'},
 p:[sel('orig','Origine',[['back','Da dietro'],['front','Da davanti']],'back'),rng('depth','Profondità',0,12,3,.1),rng('blur','Sfocatura',0,60,10,1,'px'),rng('lift','Deriva verticale',-2,2,.2,.01,'em')],
 f(s,p,u,o){const q=1-p,k=o.orig==='back'?lerp(1/(1+o.depth),1,p):lerp(1+o.depth,1,p);s.sx*=k;s.sy*=k;s.blur+=o.blur*q;s.y+=o.lift*G.E*q;s.op*=clamp(p)}},
{id:'stretch',n:'Allungamento',c:'Scala e rotazione',d:'Si stira da una linea sottile fino alla forma piena.',rec:{split:'char',stagger:.35,ease:'outBack'},
 p:[sel('ax','Asse',[['Y','Verticale'],['X','Orizzontale']],'Y'),sel('piv','Perno',PIV,'B'),rng('from','Scala iniziale',0,3,0,.01),rng('comp','Compensazione',0,1,.3,.01)],
 f(s,p,u,o){const k=lerp(o.from,1,p),c=1+(1-k)*o.comp*(o.from<1?1:-1);if(o.ax==='Y'){s.sy*=k;s.sx*=c}else{s.sx*=k;s.sy*=c}pivot(s,o.piv,u);s.op*=clamp(p*5)}},
{id:'rot',n:'Rotazione',c:'Scala e rotazione',d:'Ruota su un perno fino alla posizione dritta.',rec:{split:'char',stagger:.4,ease:'outExpo'},
 p:[rng('ang','Angolo',-360,360,-90,1,'°'),sel('piv','Perno',PIV,'B'),bool('alt','Alterna verso',false),bool('fade','Dissolvenza',true)],
 f(s,p,u,o){s.rot+=o.ang*(1-p)*(o.alt&&u.i%2?-1:1);pivot(s,o.piv,u);if(o.fade)s.op*=clamp(p*1.5)}},
{id:'flipx',n:'Ribalta',c:'Scala e rotazione',d:'Ruota in 3D sull\'asse orizzontale, come una paletta che si gira.',rec:{split:'char',stagger:.4,ease:'outCubic'},
 p:[rng('ang','Angolo',0,360,90,1,'°'),sel('piv','Perno',[['C','Centro'],['B','Base'],['T','Alto']],'C'),rng('shade','Ombra',0,1,.6,.01)],
 f(s,p,u,o){const c=Math.cos(o.ang*(1-p)*D2R);s.sy*=Math.abs(c)<.002?.002:c;pivot(s,o.piv,u);s.op*=1-(1-Math.abs(c))*o.shade;s.op*=p>0?1:0}},
{id:'flipy',n:'Giro',c:'Scala e rotazione',d:'Ruota in 3D sull\'asse verticale, come una carta che si volta.',rec:{split:'char',stagger:.4,ease:'outCubic'},
 p:[rng('ang','Angolo',0,720,180,1,'°'),sel('piv','Perno',[['C','Centro'],['L','Sinistra'],['R','Destra']],'C'),rng('shade','Ombra',0,1,.5,.01)],
 f(s,p,u,o){const c=Math.cos(o.ang*(1-p)*D2R);s.sx*=Math.abs(c)<.002?.002:c;pivot(s,o.piv,u);s.op*=1-(1-Math.abs(c))*o.shade;s.op*=p>0?1:0}},
{id:'spin',n:'Vortice',c:'Scala e rotazione',d:'Gira su se stesso crescendo fino alla posizione.',rec:{split:'char',stagger:.4,ease:'outExpo'},
 p:[rng('turns','Giri',-4,4,1,.05),rng('from','Scala iniziale',0,3,0,.01),bool('fade','Dissolvenza',true)],
 f(s,p,u,o){const k=lerp(o.from,1,p);s.rot+=o.turns*360*(1-p);s.sx*=k;s.sy*=k;if(o.fade)s.op*=clamp(p*2)}},
{id:'swing',n:'Pendolo',c:'Scala e rotazione',d:'Oscilla appeso al perno e si smorza fino a fermarsi.',rec:{split:'char',stagger:.3,ease:'linear'},
 p:[rng('amp','Ampiezza',0,150,70,1,'°'),rng('sw','Oscillazioni',.5,8,2.5,.05),rng('damp','Smorzamento',.5,5,2,.05),sel('piv','Perno',[['T','Alto'],['B','Base']],'T')],
 f(s,p,u,o){const c=clamp(p);s.rot+=o.amp*Math.pow(1-c,o.damp)*Math.cos(c*o.sw*TAU);pivot(s,o.piv,u);s.op*=clamp(c*8)}},
{id:'jelly',n:'Gelatina',c:'Scala e rotazione',d:'Schiacciamento e allungamento elastico, poggiato sulla base.',rec:{split:'char',stagger:.35,ease:'linear'},
 p:[rng('amt','Intensità',0,1.2,.55,.01),rng('wob','Oscillazioni',.5,8,3,.05),rng('damp','Smorzamento',.5,5,1.6,.05)],
 f(s,p,u,o){const c=clamp(p),g=EZ.outCubic(clamp(c*2.2)),d=o.amt*Math.pow(1-c,o.damp)*Math.sin(c*o.wob*TAU);s.sx*=g*(1+d);s.sy*=g*(1-d);pivot(s,'B',u);s.op*=c>0?1:0}},
/* --- Esplosioni --- */
{id:'explode',n:'Esplosione',c:'Esplosioni',d:'Si ricompone dai frammenti. In uscita (specchio) esplode verso l\'esterno.',rec:{split:'char',stagger:.15,ease:'outExpo'},
 p:[rng('rad','Raggio',0,20,4,.1,'em'),rng('rand','Casualità',0,1,.45,.01),rng('rot','Rotazione',0,720,200,1,'°'),rng('sc','Scala frammenti',0,3,.6,.01),rng('blur','Sfocatura',0,40,0,1,'px'),bool('fade','Dissolvenza',true)],
 f(s,p,u,o){const q=1-p;let a=Math.atan2(u.cy,u.cx);if(Math.hypot(u.cx,u.cy)<1)a=R(u,2)*TAU;a+=RS(u,3)*Math.PI*o.rand;const r=o.rad*G.E*(.55+R(u,4)*.9)*q;s.x+=Math.cos(a)*r;s.y+=Math.sin(a)*r;s.rot+=RS(u,5)*o.rot*q;const k=lerp(o.sc,1,clamp(p));s.sx*=k;s.sy*=k;s.blur+=o.blur*q;if(o.fade)s.op*=clamp(p*1.6)}},
{id:'scatter',n:'Dispersione',c:'Esplosioni',d:'I pezzi partono da punti casuali del fotogramma e si ordinano.',rec:{split:'char',stagger:.3,ease:'inOutExpo'},
 p:[rng('area','Area',0,1.5,.8,.01),rng('rot','Rotazione',0,360,60,1,'°'),rng('blur','Sfocatura',0,40,0,1,'px'),bool('fade','Dissolvenza',true)],
 f(s,p,u,o){const q=1-p;s.x+=(RS(u,6)*G.W*.5*o.area)*q;s.y+=(RS(u,16)*G.H*.5*o.area)*q;s.rot+=RS(u,17)*o.rot*q;s.blur+=o.blur*q;if(o.fade)s.op*=clamp(p*2)}},
{id:'spiral',n:'Spirale',c:'Esplosioni',d:'Arriva girando a spirale verso la posizione finale.',rec:{split:'char',stagger:.35,ease:'outCubic'},
 p:[rng('turns','Giri',0,4,1.2,.05),rng('r','Raggio',0,14,3,.1,'em'),bool('orient','Orienta sul percorso',true),rng('sc','Scala iniziale',0,2,.3,.01)],
 f(s,p,u,o){const q=1-p,a=u.i/Math.max(1,u.n)*TAU+o.turns*TAU*q,r=o.r*G.E*q;s.x+=Math.cos(a)*r;s.y+=Math.sin(a)*r;if(o.orient)s.rot+=o.turns*360*q;const k=lerp(o.sc,1,clamp(p));s.sx*=k;s.sy*=k;s.op*=clamp(p*2)}},
{id:'circle',n:'Cerchio',c:'Esplosioni',d:'Parte disposto in cerchio attorno al centro e si srotola in riga.',rec:{split:'char',stagger:.1,ease:'inOutQuart'},
 p:[rng('r','Raggio',.5,14,2.4,.1,'em'),rng('phase','Rotazione cerchio',0,360,-90,1,'°'),bool('follow','Orienta sul cerchio',true),bool('fade','Dissolvenza',false)],
 f(s,p,u,o){const q=1-p,ad=o.phase+u.i/Math.max(1,u.n)*360,a=ad*D2R,r=o.r*G.E;s.x+=(Math.cos(a)*r-u.cx)*q;s.y+=(Math.sin(a)*r-u.cy)*q;if(o.follow)s.rot+=(ad+90)*q;if(o.fade)s.op*=clamp(p)}},
/* --- Glifi --- */
{id:'type',n:'Macchina da scrivere',c:'Glifi',d:'Carattere per carattere, con cursore opzionale che lampeggia a fine riga.',rec:{split:'char',stagger:.97,ease:'linear',order:'start'},
 p:[bool('cursor','Cursore',true),sel('cur','Forma cursore',[['bar','Barra'],['block','Blocco'],['under','Trattino']],'bar'),bool('blink','Lampeggio a riposo',true),sel('cc','Colore cursore',[['B','Colore B'],['A','Colore testo']],'B')],
 f(s,p,u,o){s.op*=p>1e-4?1:0},
 post(ctx,arr,o,S,Lay,t,cols){if(!o.cursor||!arr.length)return;let last:any=null,typing=false;for(const[u,s]of arr){if(s.op>.01)last=u;else typing=true}
  let x,y;if(last){x=last.cx+last.w/2+G.E*.05;y=last.cy}else{x=arr[0][0].cx-arr[0][0].w/2;y=arr[0][0].cy}
  if(o.blink&&!typing&&Math.floor(t*1.8)%2)return;
  ctx.save();ctx.globalAlpha=1;ctx.fillStyle=o.cc==='A'?cols.A:cols.B;const b=y+Lay.base,h=Lay.capH;
  if(o.cur==='bar')ctx.fillRect(x,b-h*1.12,Math.max(1,G.E*.06),h*1.3);else if(o.cur==='block')ctx.fillRect(x,b-h*1.1,G.E*.5,h*1.26);else ctx.fillRect(x,b+G.E*.04,G.E*.5,Math.max(1,G.E*.07));ctx.restore()}},
{id:'scramble',n:'Decodifica',c:'Glifi',d:'Caratteri casuali che si risolvono nel testo, da sinistra a destra.',rec:{split:'word',stagger:.4,ease:'linear'},
 p:[sel('set','Caratteri',[['AZ','Lettere'],['n09','Numeri'],['sym','Simboli'],['bin','Binario'],['blk','Blocchi']],'AZ'),rng('rate','Cambio ogni',1,8,2,1,'frame'),bool('colB','Caratteri casuali in colore B',true),bool('fade','Dissolvenza',false)],
 f(s,p,u,o){if(p<1)s.hooks.push({fn:scrHook,p,o});s.op*=o.fade?clamp(p*2):(p>1e-4?1:0)}},
{id:'fontcycle',n:'Cambio font',c:'Glifi',d:'Ogni lettera passa rapidamente tra i font della libreria prima di fermarsi su quello scelto.',rec:{split:'char',stagger:.5,ease:'linear'},
 p:[rng('rate','Cambio ogni',1,10,3,1,'frame'),rng('hold','Assestamento',0,.9,.15,.01),bool('fade','Dissolvenza',false)],
 f(s,p,u,o){if(p<1)s.hooks.push({fn:fontHook,p,o});s.op*=o.fade?clamp(p*2):(p>1e-4?1:0)}},
{id:'weight',n:'Peso variabile',c:'Glifi',d:'Il peso del carattere scorre fino al valore finale. Funziona con i font variabili.',rec:{split:'char',stagger:.5,ease:'inOutCubic'},
 p:[rng('from','Peso iniziale',100,900,100,1),bool('fade','Dissolvenza',true),rng('lift','Deriva verticale',-1,1,0,.01,'em')],
 f(s,p,u,o){s.wght=lerp(o.from,G.wght,clamp(p));s.y+=o.lift*G.E*(1-p);if(o.fade)s.op*=clamp(p*1.5)}},
/* --- Colore e stile --- */
{id:'colorsweep',n:'Onda colore',c:'Colore e stile',d:'Il colore B attraversa il testo e lascia il colore finale, con un piccolo sollevamento.',rec:{split:'char',stagger:.6,ease:'inOutCubic'},
 p:[rng('lift','Sollevamento',-.5,.5,.08,.01,'em'),rng('sc','Pulsazione scala',0,.5,0,.01),bool('fade','Parte invisibile',false)],
 f(s,p,u,o){const q=clamp(1-p),b=Math.sin(Math.PI*clamp(p));s.mix+=q;s.y-=o.lift*G.E*b;const k=1+o.sc*b;s.sx*=k;s.sy*=k;if(o.fade)s.op*=clamp(p*3)}},
{id:'blur',n:'Messa a fuoco',c:'Colore e stile',d:'Dal fuori fuoco al nitido, con una lieve variazione di scala.',rec:{split:'word',stagger:.3,ease:'outCubic'},
 p:[rng('blur','Sfocatura',0,80,26,1,'px'),rng('sc','Scala iniziale',.5,2,1.08,.01),rng('sp','Spaziatura iniziale',0,2,0,.01,'×')],
 f(s,p,u,o){const q=1-p,k=lerp(o.sc,1,p);s.blur+=o.blur*q;s.sx*=k;s.sy*=k;s.x+=u.cx*o.sp*q;s.op*=clamp(p)}},
{id:'glitch',n:'Glitch',c:'Colore e stile',d:'Sfarfallio digitale con separazione RGB e fette sfalsate, poi si stabilizza.',rec:{split:'word',stagger:.25,ease:'linear'},
 p:[rng('int','Intensità',0,1,.7,.01),rng('rgb','Separazione RGB',0,60,12,1,'px'),rng('sl','Fette',0,16,6,1),rng('rate','Cambio ogni',1,6,2,1,'frame'),col('ca','Canale 1','#ff2a55'),col('cb','Canale 2','#00e1ff')],
 f(s,p,u,o){const q=clamp(1-p);if(q<.002)return;const k=Math.floor(G.F/o.rate);const h=j=>hash(u.i*131+k*977+j*53+G.seed);s.x+=(h(1)*2-1)*o.int*.35*G.E*q;s.rgb=o.rgb*q*o.int;s.rgbA=o.ca;s.rgbB=o.cb;if(o.sl>0&&h(2)<.75)s.slices={n:Math.round(o.sl),off:j=>(h(10+j)*2-1)*o.int*.5*G.E*q};if(h(3)<.4*q*o.int)s.op*=h(4)<.5?0:.35;s.op*=p>1e-4?1:0}},
/* --- Fisica --- (L = durata in secondi del singolo pezzo) */
{id:'gravity',n:'Gravità',c:'Fisica',exit:true,d:'Le lettere si staccano, cadono e rimbalzano sul fondo del fotogramma.',rec:{split:'char',stagger:.35,ease:'linear'},
 p:[rng('g','Gravità',2,120,34,1,'em/s²'),rng('bounce','Rimbalzo',0,.9,.42,.01),rng('kick','Spinta iniziale',0,6,1,.05,'em/s'),rng('spin','Rotazione',0,720,140,1,'°/s'),sel('floor','Pavimento',[['on','Bordo del fotogramma'],['none','Nessuno, escono']],'on'),rng('fl','Altezza pavimento',40,100,96,.5,'%')],
 f(s,p,u,o,inf){const tt=(1-p)*inf.L,g=o.g*G.E,d=floorD(u,o);const r=fall(tt,-R(u,61)*o.kick*G.E,g,d,o.bounce);s.y+=r.y;const k=d===Infinity?.05:1.4,dm=(1-Math.exp(-tt*k))/k;s.x+=RS(u,60)*o.kick*G.E*.6*dm;s.rot+=RS(u,62)*o.spin*dm}},
{id:'shatter',n:'Cade e si rompe',c:'Fisica',exit:true,d:'Cade, colpisce il fondo e si frantuma in schegge che rimbalzano.',rec:{split:'char',stagger:.3,ease:'linear'},
 p:[rng('g','Gravità',2,120,40,1,'em/s²'),rng('n','Schegge',4,80,18,1),rng('spread','Forza impatto',0,8,2.2,.05,'em/s'),rng('spin','Rotazione schegge',0,1440,420,1,'°/s'),rng('life','Durata schegge',.1,4,1.1,.05,'s'),rng('jit','Attesa casuale',0,1.5,.25,.01,'s'),rng('fl','Altezza pavimento',40,100,94,.5,'%')],
 f(s,p,u,o,inf){const tt=(1-p)*inf.L-R(u,63)*o.jit;if(tt<=0)return;const g=o.g*G.E,d=Math.max(0,G.H*o.fl/100-(u.fy+u.by1)),th=Math.sqrt(2*d/g);
  if(tt<th){s.y+=.5*g*tt*tt;s.rot+=RS(u,64)*6*clamp(tt/.3);return}
  s.y+=d;const dt=tt-th,E=G.E,hw=u.w/2+1;
  s.frag={pieces:pieces(u,o.n),fn:pc=>{const k=pc.k,h=j=>hash(u.i*131+k*71+j*13+G.seed),sp=o.spread*E;const vx=(pc.cx/hw)*sp*(.3+h(1)*.9)+(h(2)-.5)*sp*.7,vy=-(.2+h(3))*sp*1.2;const r=fall(dt,vy,g,Math.max(0,u.by1-pc.cy),.28);const ta=r.first>=0?r.first+(1-Math.exp(-(dt-r.first)*4))/4:dt;return{x:vx*ta,y:r.y,r:(h(4)-.5)*o.spin*ta,op:1-clamp((dt-o.life)/.6)}}}}},
{id:'crumble',n:'Sgretolamento',c:'Fisica',exit:true,d:'Il testo si sbriciola in tanti frammenti che cadono come sabbia.',rec:{split:'word',stagger:.25,ease:'linear'},
 p:[sel('dir','Parte da',[['L','Sinistra'],['R','Destra'],['T','Alto'],['B','Basso'],['RND','Casuale']],'L'),rng('n','Frammenti',8,160,70,1),rng('g','Gravità',2,120,30,1,'em/s²'),rng('sweep','Durata spazzata',0,3,.8,.01,'s'),rng('drift','Deriva',0,3,.5,.01,'em/s'),rng('spin','Rotazione',0,1080,260,1,'°/s'),rng('life','Dissolvenza',.1,4,1,.05,'s')],
 f(s,p,u,o,inf){const tt=(1-p)*inf.L,g=o.g*G.E,E=G.E,w=u.w||1,h0=(u.by1-u.by0)||1;
  s.frag={pieces:pieces(u,o.n),fn:pc=>{const k=pc.k,h=j=>hash(u.i*97+k*53+j*11+G.seed);const nx=(pc.cx+w/2)/w,ny=(pc.cy-u.by0)/h0;const pos=o.dir==='L'?nx:o.dir==='R'?1-nx:o.dir==='T'?ny:o.dir==='B'?1-ny:h(9);const dt=tt-(pos*o.sweep+h(1)*.15);if(dt<=0)return{x:0,y:0,r:0,op:1};return{x:(h(2)-.5)*o.drift*E*dt*2,y:-h(3)*.15*E*dt+.5*g*dt*dt,r:(h(4)-.5)*o.spin*dt,op:1-clamp(dt/o.life)}}}}},
{id:'zerog',n:'Assenza di gravità',c:'Fisica',exit:true,d:'Le lettere si staccano e fluttuano lentamente verso l\'alto, ruotando.',rec:{split:'char',stagger:.4,ease:'linear'},
 p:[rng('rise','Salita',-3,3,.5,.01,'em/s'),rng('acc','Accelerazione',-3,3,.25,.01),rng('spread','Dispersione',0,3,.35,.01,'em/s'),rng('drift','Ondeggiamento',0,1,.12,.005,'em'),rng('spin','Rotazione',0,360,40,1,'°/s'),rng('life','Visibile per',.1,10,1.4,.05,'s'),rng('fadeT','Dissolvenza',.05,4,.8,.05,'s')],
 f(s,p,u,o,inf){const tt=(1-p)*inf.L,E=G.E,v=.6+R(u,65)*.8;s.y-=(o.rise*tt+.5*o.acc*tt*tt)*E*v;s.x+=RS(u,66)*o.spread*E*tt+Math.sin(tt*1.7+R(u,67)*TAU)*o.drift*E*clamp(tt*2);s.rot+=RS(u,68)*o.spin*tt;s.op*=1-clamp((tt-o.life)/o.fadeT)}},
{id:'wind',n:'Vento',c:'Fisica',exit:true,d:'Una raffica porta via le lettere come fogli, con svolazzo e rotazione.',rec:{split:'char',stagger:.45,ease:'linear'},
 p:[sel('dir','Verso',[['R','Verso destra'],['L','Verso sinistra']],'R'),rng('str','Forza',0,80,18,.5,'em/s²'),rng('lift','Portanza',-10,20,3,.1,'em/s²'),rng('turb','Turbolenza',0,1,.25,.01,'em'),rng('spin','Rotazione',0,1080,300,1,'°/s'),rng('flip','Svolazzo',0,1,.6,.01)],
 f(s,p,u,o,inf){const tt=(1-p)*inf.L,E=G.E,d=o.dir==='L'?-1:1,v=.6+R(u,70)*.8;s.x+=d*.5*o.str*v*tt*tt*E;s.y+=(Math.sin(tt*4+R(u,71)*TAU)*o.turb*clamp(tt*3)-.5*o.lift*v*tt*tt)*E;s.rot+=d*o.spin*(.5+R(u,72))*tt*.5*tt;s.sx*=lerp(1,Math.cos(tt*(3+R(u,73)*4)),clamp(tt*2)*o.flip)}},
{id:'hinge',n:'Cerniera',c:'Fisica',exit:true,d:'La lettera perde un chiodo: resta appesa a un angolo, oscilla e poi cade.',rec:{split:'char',stagger:.5,ease:'linear'},
 p:[sel('side','Angolo che tiene',[['RND','Casuale'],['L','Sinistro'],['R','Destro']],'RND'),rng('hang','Resta appeso',0,4,.9,.01,'s'),rng('damp','Smorzamento',.5,8,2.4,.05),rng('freq','Oscillazione',.2,4,1.2,.05,'Hz'),rng('g','Gravità',2,120,36,1,'em/s²')],
 f(s,p,u,o,inf){const tt=(1-p)*inf.L,side=o.side==='L'?-1:o.side==='R'?1:(R(u,74)<.5?-1:1);s.px=side*u.w/2;s.py=u.by0+G.E*.08;const td=o.hang+R(u,75)*.3;const th=x=>90*(1-Math.exp(-o.damp*x)*Math.cos(o.freq*TAU*x));
  if(tt<td){s.rot+=-side*th(tt)}else{const tf=tt-td;s.rot+=-side*(th(td)+tf*tf*40);s.y+=.5*o.g*G.E*tf*tf}}},
{id:'land',n:'Atterraggio',c:'Fisica',d:'Cade dall\'alto sulla propria base, rimbalza e si schiaccia all\'impatto.',rec:{split:'char',stagger:.45,ease:'linear'},
 p:[rng('h','Altezza',.5,15,3.5,.05,'em'),rng('g','Gravità',2,160,55,1,'em/s²'),rng('rest','Rimbalzo',0,.8,.38,.01),rng('sq','Schiacciamento',0,.8,.35,.01),rng('rot','Rotazione in volo',0,90,0,1,'°')],
 f(s,p,u,o,inf){const el=clamp(p)*inf.L,g=o.g*G.E,h=o.h*G.E;const r=fall(el,0,g,h,o.rest);s.y+=-h+r.y;if(r.first<0)s.rot+=RS(u,76)*o.rot*(1-r.y/h);if(r.lastI>=0){const since=el-r.lastI,sq=o.sq*clamp(r.lastV/Math.sqrt(2*g*h))*Math.exp(-since*11)*Math.cos(since*22);s.sy*=1-sq;s.sx*=1+sq*.7;pivot(s,'B',u)}s.op*=p>1e-4?1:0}},
{id:'burst',n:'Detonazione',c:'Fisica',exit:true,d:'Esplode dal centro con traiettorie a parabola che ricadono fuori campo.',rec:{split:'char',stagger:.05,ease:'linear'},
 p:[rng('pow','Potenza',0,40,12,.1,'em/s'),rng('up','Spinta verso l\'alto',0,30,6,.1,'em/s'),rng('g','Gravità',0,120,30,1,'em/s²'),rng('rand','Casualità',0,1,.4,.01),rng('spin','Rotazione',0,1440,500,1,'°/s'),rng('zoom','Verso la camera',0,3,.4,.01)],
 f(s,p,u,o,inf){const tt=(1-p)*inf.L,E=G.E;let a=Math.atan2(u.cy,u.cx);if(Math.hypot(u.cx,u.cy)<1)a=R(u,77)*TAU;a+=RS(u,78)*Math.PI*o.rand;const v=o.pow*E*(.6+R(u,79)*.8);const dm=(1-Math.exp(-tt*.9))/.9;s.x+=Math.cos(a)*v*dm;s.y+=(Math.sin(a)*v-o.up*E)*dm+.5*o.g*E*tt*tt;s.rot+=RS(u,80)*o.spin*tt;const k=1+o.zoom*tt*R(u,81);s.sx*=k;s.sy*=k}},
{id:'melt',n:'Scioglimento',c:'Fisica',exit:true,d:'Il testo cola verso il basso a strisce, come vernice fresca.',rec:{split:'word',stagger:.3,ease:'linear'},
 p:[rng('n','Strisce',4,120,40,1),rng('len','Colatura',0,12,3,.05,'em'),rng('sink','Affondamento',0,6,.6,.05,'em'),rng('blur','Sfocatura',0,20,0,.5,'px'),bool('fade','Dissolvenza finale',true)],
 f(s,p,u,o,inf){const pr=clamp(1-p),n=Math.round(o.n),e=EZ.inCubic(pr);s.vs={n,off:j=>{const r=hash(u.i*29+j*7+G.seed);return(r*r*.85+.15)*o.len*G.E*e}};s.y+=o.sink*G.E*EZ.inQuad(pr);s.blur+=o.blur*pr;if(o.fade)s.op*=1-clamp((pr-.65)/.35)}},
/* --- Trend 2026 --- */
{id:'blurlift',n:'Salita sfocata',c:'Trend 2026',d:'Sale dal basso uscendo dallo sfocato, morbido e pulito come le presentazioni prodotto.',rec:{split:'char',stagger:.3,ease:'outQuart'},
 p:[rng('dist','Salita',0,3,.35,.01,'em'),rng('blur','Sfocatura',0,60,18,1,'px'),rng('sc','Scala iniziale',.5,1.5,.92,.01)],
 f(s,p,u,o){const q=1-p,k=lerp(o.sc,1,p);s.y+=o.dist*G.E*q;s.blur+=o.blur*q;s.sx*=k;s.sy*=k;s.op*=clamp(p*1.4)}},
{id:'flap',n:'Tabellone',c:'Trend 2026',d:'Le palette di un tabellone da stazione girano su caratteri casuali fino a quello giusto.',rec:{split:'char',stagger:.4,ease:'outCubic'},
 p:[rng('flips','Giri',1,20,6,1),sel('set','Caratteri',[['AZ','Lettere'],['n09','Numeri'],['sym','Simboli']],'AZ'),rng('shade','Ombra',0,1,.5,.01)],
 f(s,p,u,o){const r=clamp(1-p)*o.flips,k=Math.floor(r),fr=r-k,c=Math.abs(Math.cos(fr*Math.PI));s.sy*=Math.max(.02,c);s.op*=(1-(1-c)*o.shade)*(p>1e-4?1:0);const kk=k+(fr>.5?1:0);if(kk>0)s.hooks.push({fn:flapHook,p:kk,o})}},
{id:'dolly',n:'Carrellata 3D',c:'Trend 2026',d:'Ogni lettera arriva da una profondità diversa verso il punto di fuga, come una camera che avanza.',rec:{split:'char',stagger:.2,ease:'outExpo'},
 p:[rng('depth','Profondità',0,10,4,.1),rng('var','Varietà',0,1,.6,.01),rng('blur','Sfocatura',0,40,6,1,'px')],
 f(s,p,u,o){const q=1-p,z=Math.max(0,o.depth*(1-o.var+o.var*R(u,101)*2)*q),k=1/(1+z);s.x+=u.cx*(k-1);s.y+=u.cy*(k-1);s.sx*=k;s.sy*=k;s.blur+=o.blur*q;s.op*=clamp(p*2)}},
{id:'ripple',n:'Increspatura',c:'Trend 2026',d:'Un\'onda circolare parte dal centro e si propaga sulle lettere, come un sasso nell\'acqua.',rec:{split:'char',stagger:.4,ease:'outCubic',order:'center'},
 p:[rng('amp','Ampiezza',0,3,.6,.01,'em'),rng('freq','Frequenza',0,3,1,.01),rng('cyc','Onde',0,6,2,.1)],
 f(s,p,u,o){const q=1-p,d=Math.hypot(u.cx,u.cy)/G.E,w=Math.sin(d*o.freq-q*o.cyc*TAU)*q;s.y+=w*o.amp*G.E;const k=1+w*.12;s.sx*=k;s.sy*=k;s.op*=clamp(p*2)}},
{id:'liquid',n:'Liquido',c:'Trend 2026',d:'Il testo si ricompone da strisce ondulate, come un riflesso sull\'acqua che si calma.',rec:{split:'word',stagger:.25,ease:'outCubic'},
 p:[rng('n','Strisce',4,120,36,1),rng('amp','Ampiezza',0,4,1.2,.01,'em'),rng('freq','Frequenza',0,2,.35,.01),rng('blur','Sfocatura',0,20,2,.5,'px')],
 f(s,p,u,o){const q=clamp(1-p),n=Math.round(o.n);s.vs={n,off:j=>Math.sin(j*o.freq+q*6+u.i)*o.amp*G.E*q*q};s.blur+=o.blur*q;s.op*=clamp(p*2)}},
{id:'mosaic',n:'Mosaico',c:'Trend 2026',d:'Il testo si compone a tessere che appaiono in ordine casuale.',rec:{split:'word',stagger:.3,ease:'linear'},
 p:[rng('n','Tessere',8,200,60,1),rng('soft','Morbidezza',0,1,.3,.01),rng('lift','Sollevamento',0,.5,.06,.01,'em')],
 f(s,p,u,o){const w=Math.max(.02,o.soft);s.frag={pieces:pieces(u,o.n),fn:pc=>{const h=hash(u.i*37+pc.k*101+G.seed),a=clamp((p-h*(1-w))/w);return{x:0,y:(1-a)*o.lift*G.E,r:0,op:a}}}}},
{id:'shards',n:'Vetro',c:'Trend 2026',d:'Schegge di vetro volano da tutte le direzioni e si incastrano a formare le lettere.',rec:{split:'char',stagger:.3,ease:'outExpo'},
 p:[rng('n','Schegge',4,80,24,1),rng('dist','Distanza',0,10,2.5,.05,'em'),rng('rot','Rotazione',0,720,180,1,'°'),rng('jit','Casualità tempo',0,1,.4,.01)],
 f(s,p,u,o){s.frag={pieces:pieces(u,o.n),fn:pc=>{const h=j=>hash(u.i*53+pc.k*71+j*17+G.seed),d0=h(5)*o.jit*.5,a=clamp((p-d0)/(1-d0)),qq=1-a,an=Math.atan2(pc.cy,pc.cx)+(h(1)-.5)*1.5,r=o.dist*G.E*(.4+h(2))*qq;return{x:Math.cos(an)*r,y:Math.sin(an)*r,r:(h(3)-.5)*2*o.rot*qq,op:clamp(a*3)}}}}},
{id:'chroma',n:'Aberrazione cromatica',c:'Trend 2026',d:'Canali colore separati che convergono mentre il testo va a fuoco.',rec:{split:'word',stagger:.25,ease:'outExpo'},
 p:[rng('rgb','Separazione',0,120,40,1,'px'),rng('blur','Sfocatura',0,40,8,1,'px'),rng('sc','Scala iniziale',.8,2,1.15,.01),col('ca','Canale 1','#ff2a55'),col('cb','Canale 2','#00e1ff')],
 f(s,p,u,o){const q=clamp(1-p),k=lerp(o.sc,1,p);s.rgb=o.rgb*q;s.rgbA=o.ca;s.rgbB=o.cb;s.blur+=o.blur*q;s.sx*=k;s.sy*=k;s.op*=clamp(p*1.5)}},
{id:'echo',n:'Eco',c:'Trend 2026',d:'Scorre lasciando una scia di copie che si raccolgono all\'arrivo.',rec:{split:'char',stagger:.35,ease:'outExpo'},
 p:[sel('dir','Provenienza',DIRS.slice(0,8),'B'),rng('dist','Distanza',0,8,2,.01,'em'),rng('n','Copie',1,12,5,1),rng('gap','Scia',0,2,.35,.01,'em'),rng('a','Opacità scia',0,1,.5,.01)],
 f(s,p,u,o){const q=1-p,[x,y]=dv(o.dir,u);s.x+=x*o.dist*G.E*q;s.y+=y*o.dist*G.E*q;s.echo={n:Math.round(o.n),dx:x*o.gap*G.E*q,dy:y*o.gap*G.E*q,a:o.a*clamp(q*4)};s.op*=clamp(p*3)}},
{id:'flicker',n:'Accensione neon',c:'Trend 2026',d:'Le lettere si accendono a scatti come un\'insegna al neon che parte.',rec:{split:'char',stagger:.6,ease:'linear'},
 p:[rng('hz','Frequenza',1,30,16,1,'Hz'),rng('dim','Luminosità spenta',0,1,.08,.01),bool('colB','Parte dal colore B',false)],
 f(s,p,u,o){const k=Math.floor(G.t*o.hz),on=hash(u.i*191+k*37+G.seed)<p*p;s.op*=p>1e-4?(on?1:o.dim):0;if(o.colB)s.mix+=clamp(1-p)}},
{id:'cube',n:'Cubo 3D',c:'Trend 2026',d:'Il testo ruota come la faccia di un cubo, dentro una maschera.',rec:{split:'word',stagger:.2,ease:'outQuart'},
 p:[sel('dir','Verso',[['U','Verso l\'alto'],['D','Verso il basso']],'U'),rng('depth','Profondità',0,2,1,.01),rng('shade','Ombra',0,1,.6,.01),bool('mask','Maschera',true)],
 f(s,p,u,o){const th=clamp(1-p,-.5,1)*Math.PI/2,c=Math.cos(th),hh=u.by1-u.by0;if(o.mask)s.clip=1;s.sy*=Math.max(.002,c);s.y+=(o.dir==='U'?1:-1)*Math.sin(th)*hh*.5*o.depth;s.op*=1-(1-c)*o.shade}},
{id:'smear',n:'Scatto con scia',c:'Trend 2026',d:'Arriva di scatto, allungato dalla velocità, poi torna alla forma normale.',rec:{split:'char',stagger:.3,ease:'outExpo'},
 p:[sel('dir','Provenienza',DIR4,'L'),rng('dist','Distanza',0,10,3,.05,'em'),rng('amt','Allungamento',0,4,1.5,.01),rng('blur','Sfocatura',0,30,4,1,'px')],
 f(s,p,u,o){const q=1-p,[x,y]=dv(o.dir,u),c=clamp(p),st=o.amt*4*c*(1-c);s.x+=x*o.dist*G.E*q;s.y+=y*o.dist*G.E*q;if(x){s.sx*=1+st;s.sy*=1/(1+st*.3)}else{s.sy*=1+st;s.sx*=1/(1+st*.3)}s.blur+=o.blur*clamp(q);s.op*=clamp(p*3)}},
{id:'outline',n:'Dal contorno',c:'Trend 2026',d:'Appare solo il contorno, poi le lettere si riempiono.',rec:{split:'char',stagger:.5,ease:'inOutCubic'},
 p:[rng('w','Spessore',.2,10,1.5,.1,'% em'),rng('sc','Scala iniziale',.8,1.3,1,.01),rng('blur','Sfocatura',0,20,0,1,'px')],
 f(s,p,u,o){const q=clamp(1-p),k=lerp(o.sc,1,p);s.outl=q;s.outlW=Math.max(.5,o.w/100*G.E);s.sx*=k;s.sy*=k;s.blur+=o.blur*q;s.op*=clamp(p*6)}},
{id:'hop',n:'Salto',c:'Trend 2026',d:'Ogni lettera salta al suo posto con un arco e si schiaccia all\'atterraggio.',rec:{split:'char',stagger:.4,ease:'linear'},
 p:[sel('dir','Da',[['L','Da sinistra'],['R','Da destra']],'L'),rng('dist','Distanza',0,6,1,.01,'em'),rng('h','Altezza salto',0,6,1.2,.01,'em'),rng('sq','Schiacciamento',0,.6,.2,.01),rng('rot','Rotazione',0,360,0,1,'°')],
 f(s,p,u,o){const c=clamp(p),v=o.dir==='L'?-1:1;s.x+=v*o.dist*G.E*(1-c);s.y-=o.h*G.E*4*c*(1-c);s.rot+=v*o.rot*(1-c);if(c>.85){const sq=o.sq*Math.sin((c-.85)/.15*Math.PI);s.sy*=1-sq;s.sx*=1+sq*.6;pivot(s,'B',u)}s.op*=clamp(c*5)}},
{id:'rain',n:'Pioggia digitale',c:'Trend 2026',d:'Caratteri casuali cadono dall\'alto e si trasformano nel testo all\'arrivo.',rec:{split:'char',stagger:.7,ease:'outCubic',order:'random'},
 p:[rng('h','Caduta',0,20,4,.1,'em'),sel('set','Caratteri',[['bin','Binario'],['AZ','Lettere'],['n09','Numeri'],['blk','Blocchi'],['sym','Simboli']],'bin'),rng('rate','Cambio ogni',1,8,2,1,'frame'),bool('colB','Colore B in caduta',true)],
 f(s,p,u,o){s.y-=o.h*G.E*(1-p);if(p<1)s.hooks.push({fn:rainHook,p,o});s.op*=clamp(p*3)}},
{id:'vortex',n:'Risucchio',c:'Trend 2026',d:'Le lettere escono da un vortice al centro e si srotolano in riga.',rec:{split:'char',stagger:.15,ease:'outCubic'},
 p:[rng('turns','Giri',-3,3,.75,.05),rng('sc','Scala iniziale',0,1,0,.01),rng('blur','Sfocatura',0,30,0,1,'px')],
 f(s,p,u,o){const q=1-p,a=o.turns*TAU*q,c=Math.cos(a),sn=Math.sin(a),k=lerp(o.sc,1,p);s.x+=(u.cx*c-u.cy*sn)*p-u.cx;s.y+=(u.cx*sn+u.cy*c)*p-u.cy;s.rot+=a/D2R;s.sx*=k;s.sy*=k;s.blur+=o.blur*clamp(q);s.op*=clamp(p*3)}},
{id:'stamp',n:'Timbro',c:'Trend 2026',d:'Cala dall\'alto come un timbro e fa tremare il fotogramma all\'impatto.',rec:{split:'word',stagger:.3,ease:'linear'},
 p:[rng('from','Scala iniziale',1,6,2.6,.01,'×'),rng('rot','Rotazione',-45,45,-8,1,'°'),rng('shake','Scossa',0,1,.35,.01,'em'),rng('blur','Sfocatura',0,30,6,1,'px')],
 f(s,p,u,o){const c=clamp(p),pre=Math.min(1,c/.55),k=lerp(o.from,1,EZ.inQuad(pre));s.sx*=k;s.sy*=k;s.rot+=o.rot*(1-pre);s.blur+=o.blur*(1-pre);if(c>=.55){const z=(c-.55)/.45,e=Math.exp(-z*6);s.x+=Math.sin(z*50)*o.shake*G.E*e*.3;s.y+=Math.cos(z*43)*o.shake*G.E*e*.2}s.op*=clamp(pre*3)}},
{id:'counter',n:'Contatore',c:'Trend 2026',d:'Numeri e lettere scorrono in sequenza (0-9, A-Z) fino al carattere finale.',rec:{split:'char',stagger:.3,ease:'outCubic'},
 p:[rng('spins','Giri',0,10,2,1)],
 f(s,p,u,o){if(p<1)s.hooks.push({fn:cntHook,p,o});s.op*=p>1e-4?1:0}},
{id:'scan',n:'Scansione',c:'Trend 2026',d:'Una linea di scansione attraversa il testo e lo rivela, con un leggero disturbo.',rec:{split:'word',stagger:.2,ease:'linear'},
 p:[sel('dir','Direzione',[['T','Dall\'alto'],['B','Dal basso'],['L','Da sinistra'],['R','Da destra']],'T'),rng('jit','Disturbo',0,1,.3,.01),bool('line','Linea di scansione',true),bool('colB','Parte dal colore B',true)],
 f(s,p,u,o){const q=clamp(1-p),a=clamp(p);s.wipe={d:o.dir,a,soft:0};if(o.colB)s.mix+=clamp(q*1.5);s.x+=(hash(u.i*7+G.F*13+G.seed)-.5)*o.jit*G.E*.2*q;if(o.line&&a>0&&a<1)s.bar={d:o.dir,a:Math.max(0,a-.025),b:a,c:'B',pad:0}}},
{id:'blocks',n:'Pixel a blocchi',c:'Trend 2026',d:'Ogni lettera passa da blocchi pieni a sfumati (█▓▒░) prima di apparire, in stile Y2K.',rec:{split:'char',stagger:.5,ease:'linear'},
 p:[rng('steps','Passaggi',1,4,4,1),bool('colB','Blocchi in colore B',false)],
 f(s,p,u,o){if(p<1)s.hooks.push({fn:blkHook,p,o});s.op*=p>1e-4?1:0}},
/* --- Cinetica --- */
{id:'rowsopp',n:'Righe opposte',c:'Cinetica',d:'Le righe entrano da lati opposti: la prima da sinistra, la seconda da destra, e così via. Con un angolo la traiettoria si inclina.',rec:{split:'line',stagger:.3,ease:'outExpo'},
 p:[rng('dist','Distanza',0,60,16,.1,'em'),rng('ang','Angolo',-60,60,0,1,'°'),bool('fade','Dissolvenza',false),bool('first','Parte da destra',false)],
 f(s,p,u,o){const q=1-p,v=((u.line%2)^(o.first?1:0))?1:-1,a=o.ang*D2R;s.x+=v*Math.cos(a)*o.dist*G.E*q;s.y+=v*Math.sin(a)*o.dist*G.E*q;if(o.fade)s.op*=clamp(p*1.6)}},
{id:'wipeopp',n:'Tendine opposte',c:'Cinetica',d:'Una tendina scopre ogni riga alternando il verso: da sinistra, da destra, da sinistra…',rec:{split:'line',stagger:.3,ease:'inOutQuart'},
 p:[rng('edge','Bordo morbido',0,1,0,.01),bool('first','Parte da destra',false)],
 f(s,p,u,o){s.wipe={d:((u.line%2)^(o.first?1:0))?'R':'L',a:clamp(p),soft:o.edge}}},
{id:'diagwipe',n:'Rivelazione diagonale',c:'Cinetica',d:'Una tendina inclinata scopre il testo. L\'angolo decide da dove arriva il taglio.',rec:{split:'word',stagger:.25,ease:'inOutQuart'},
 p:[rng('ang','Angolo',-180,180,-30,1,'°'),bool('fade','Dissolvenza',false)],
 f(s,p,u,o){s.dwipe={ang:o.ang,a:clamp(p)};if(o.fade)s.op*=clamp(p*2)}},
{id:'settle',n:'Scossa che si calma',c:'Cinetica',d:'Il testo vibra con forza e si assesta, come un colpo che si smorza.',rec:{split:'word',stagger:.2,ease:'linear'},
 p:[rng('amp','Ampiezza',0,3,.35,.01,'em'),rng('rot','Rotazione',0,30,5,.1,'°'),rng('hz','Frequenza',1,40,18,1,'Hz'),rng('damp','Smorzamento',.5,6,2.2,.1)],
 f(s,p,u,o){const c=clamp(p),q=Math.pow(1-c,o.damp),k=Math.floor(G.t*o.hz);s.x+=RS(u,k*5+201)*o.amp*G.E*q;s.y+=RS(u,k*5+202)*o.amp*G.E*q;s.rot+=RS(u,k*5+203)*o.rot*q;s.op*=c>0?1:0}},
{id:'hroll',n:'Rullo orizzontale',c:'Cinetica',d:'Ogni carattere scorre di lato come un rullo, passando per caratteri casuali prima di fermarsi.',rec:{split:'char',stagger:.35,ease:'outCubic'},
 p:[rng('spins','Giri',1,30,6,1),sel('dir','Verso',[['R','Verso destra'],['L','Verso sinistra']],'R'),sel('set','Caratteri',[['AZ','Lettere'],['n09','Numeri'],['sym','Simboli']],'AZ')],
 f(s,p,u,o){s.clip=1;const r=clamp(1-p,0,1)*o.spins,k=Math.floor(r);s.hroll={k,frac:r-k,dir:o.dir==='R'?1:-1,set:o.set};s.op*=p>0?1:0}},
{id:'fold',n:'Piega',c:'Cinetica',d:'Le lettere si aprono come un foglio piegato, con un\'ombra sul lato che gira.',rec:{split:'char',stagger:.4,ease:'outCubic'},
 p:[sel('dir','Perno',[['L','Sinistra'],['R','Destra']],'L'),rng('ang','Angolo',0,89,75,1,'°'),rng('shade','Ombra',0,1,.55,.01)],
 f(s,p,u,o){const th=(1-clamp(p))*o.ang*D2R,c=Math.cos(th),sd=o.dir==='L'?-1:1;s.px=sd*u.w/2;s.sx*=Math.max(.002,c);s.skx+=sd*Math.sin(th)*22;s.op*=(1-(1-c)*o.shade)*(p>0?1:0)}},
{id:'pulse',n:'Impulso ritmico',c:'Cinetica',d:'La scala pulsa più volte con ampiezza decrescente prima di assestarsi.',rec:{split:'word',stagger:.25,ease:'linear'},
 p:[rng('n','Impulsi',1,8,3,1),rng('amp','Intensità',0,1.5,.35,.01),rng('damp','Smorzamento',.2,4,1.4,.05),sel('piv','Perno',PIV,'C')],
 f(s,p,u,o){const c=clamp(p),k=1+o.amp*Math.pow(1-c,o.damp)*Math.sin(c*o.n*TAU),g=Math.min(1,c*6);s.sx*=k*g;s.sy*=k*g;pivot(s,o.piv,u);s.op*=c>0?1:0}},
{id:'flashcut',n:'Taglio con flash',c:'Cinetica',d:'Le parole compaiono di scatto, per un istante più grandi e nel colore B, poi tornano normali. Tipico dei sottotitoli.',rec:{split:'word',stagger:.6,ease:'linear'},
 p:[rng('sc','Scala iniziale',1,2,1.25,.01,'×'),rng('hold','Durata del flash',.02,.5,.18,.01),bool('colB','Flash in colore B',true)],
 f(s,p,u,o){if(p<=1e-4){s.op*=0;return}const c=clamp(p),fl=1-clamp(c/o.hold),k=1+(o.sc-1)*fl;s.sx*=k;s.sy*=k;if(o.colB)s.mix+=fl}},
{id:'underline',n:'Sottolineatura',c:'Cinetica',d:'Una linea si disegna sotto il testo mentre compare e resta come sottolineatura.',rec:{split:'word',stagger:.3,ease:'outExpo'},
 p:[rng('th','Spessore',.01,.3,.07,.005,'em'),rng('off','Distanza',-.2,.6,.14,.005,'em'),sel('col','Colore',[['B','Colore B'],['A','Colore testo']],'B')],
 f(s,p,u,o){s.ul=clamp(p);s.op*=clamp((p-.1)*2.2)},
 post(ctx,arr,o,S,Lay,t,cols){ctx.save();ctx.fillStyle=o.col==='B'?cols.B:cols.A;for(const[u,s]of arr){const a=s.ul===undefined?1:s.ul;if(a<=.001||s.op<=.01)continue;ctx.globalAlpha=Math.min(1,s.op);ctx.fillRect(u.cx-u.w/2,u.cy+Lay.base+o.off*G.E,u.w*a,Math.max(1,o.th*G.E))}ctx.restore()}},
{id:'outlinedraw',n:'Contorno disegnato',c:'Cinetica',d:'Il contorno delle lettere si disegna a tratto e poi si riempie.',rec:{split:'char',stagger:.5,ease:'inOutCubic'},
 p:[rng('w','Spessore',.2,10,2.5,.1,'% em'),rng('stage','Quota di disegno',.3,.95,.75,.01)],
 f(s,p,u,o){const c=clamp(p);s.dash={f:clamp(c/o.stage),len:G.E*8};s.outl=1-clamp((c-o.stage)/(1-o.stage));s.outlW=Math.max(.8,o.w/100*G.E);s.op*=c>0?1:0}},
{id:'blurspin',n:'Giro sfocato',c:'Cinetica',d:'Ogni lettera gira su se stessa uscendo dallo sfocato e cresce fino alla posizione.',rec:{split:'char',stagger:.4,ease:'outExpo'},
 p:[rng('turns','Giri',-3,3,.75,.05),rng('blur','Sfocatura',0,60,22,1,'px'),rng('sc','Scala iniziale',0,2,.6,.01)],
 f(s,p,u,o){const q=1-p,k=lerp(o.sc,1,p);s.rot+=o.turns*360*q;s.blur+=o.blur*q;s.sx*=k;s.sy*=k;s.op*=clamp(p*2.5)}},
{id:'glowin',n:'Bagliore',c:'Cinetica',d:'Il testo si accende con un bagliore che sale e poi si spegne, con una lieve salita.',rec:{split:'word',stagger:.3,ease:'outCubic'},
 p:[rng('blur','Bagliore',0,3,1.1,.01,'em'),sel('col','Colore',[['B','Colore B'],['A','Colore testo']],'B'),rng('lift','Salita',0,1,.12,.01,'em')],
 f(s,p,u,o){const c=clamp(p);s.glow={blur:o.blur*G.E*Math.sin(Math.PI*c),c:o.col,a:1};s.y+=o.lift*G.E*(1-c);s.op*=clamp(c*3)}},
...walkFx(),
...pathFx(),
];

/* --- Traiettorie: il testo arriva (o se ne va) lungo una curva, da qualunque direzione ---
   Distanza, curvatura e raggio sono in % del quadro (lungo la direzione di marcia o di traverso), così il movimento è visibile qualunque sia la grandezza del testo. */
function pathFx(): EffectDef[] {
  const mk = (shape: PathShape, id: string, n: string, d: string, ext: ParamDef[]): EffectDef => ({
    id, n, c: 'Voli curvi', d, rec: { split: 'char', stagger: .35, ease: 'outCubic' },
    p: [sel('from', 'Provenienza', [...DIRS, ['ANG', 'Angolo libero']], 'L'), rng('ang', 'Angolo di marcia', -180, 180, 0, 1, '°'), rng('D', 'Distanza', 0, 150, 60, 1, '% quadro'), ...ext,
      rng('follow', 'Segue la curva', 0, 1, .5, .01), bool('alt', 'Alterna il lato', false), bool('fade', 'Dissolvenza', true)],
    f(s, p, u, o) {
      const dvv = o.from === 'ANG' ? [-Math.cos(o.ang * D2R), -Math.sin(o.ang * D2R)] : dv(o.from, u);
      const tx = -dvv[0], ty = -dvv[1], side = o.alt && u.i % 2 ? -1 : 1;
      const spanA = Math.abs(tx) * G.W + Math.abs(ty) * G.H, spanB = Math.abs(ty) * G.W + Math.abs(tx) * G.H;
      const P = { D: o.D / 100 * spanA, amp: (o.amp ?? 0) / 100 * spanB, cyc: o.cyc ?? 1, R: (o.R ?? 0) / 100 * Math.min(G.W, G.H), loops: o.loops ?? 1 };
      const r = pathOffset(shape, p, P, tx, ty, side, 1);
      s.x += r.x; s.y += r.y;
      if (o.follow > 0) s.rot += pathAngle(shape, p, P) * side * o.follow * (1 - clamp(p));
      if (o.fade) s.op *= clamp(p * 2.2);
    },
  });
  return [
    mk('arc', 'patharc', 'Arco', 'Arriva lungo un arco, da qualunque lato o con un angolo libero. In uscita fa lo stesso al contrario.', [rng('amp', 'Curvatura', -80, 80, 25, 1, '% quadro')]),
    mk('wave', 'pathwave', 'Onda', 'Arriva ondeggiando, come lungo una sinusoide che si calma all\'arrivo.', [rng('amp', 'Ampiezza', -60, 60, 10, 1, '% quadro'), rng('cyc', 'Onde', .5, 6, 2, .5)]),
    mk('loop', 'pathloop', 'Cerchio', 'Arriva facendo uno o più giri a cerchio, come un anello lungo il percorso.', [rng('R', 'Raggio del giro', 0, 60, 22, 1, '% quadro'), rng('loops', 'Giri', 1, 4, 1, 1)]),
    mk('s', 'paths', 'Curva a S', 'Arriva con una curva a S: prima da un lato, poi dall\'altro.', [rng('amp', 'Ampiezza', -80, 80, 20, 1, '% quadro')]),
    mk('zig', 'pathzig', 'Zigzag', 'Arriva a zigzag, con scatti da un lato all\'altro.', [rng('amp', 'Ampiezza', -60, 60, 10, 1, '% quadro'), rng('cyc', 'Zig', .5, 8, 3, .5)]),
  ];
}

/* --- Su tracciato: le lettere entrano camminando lungo il tracciato scelto nel movimento continuo (arco, cerchio, onda…) ---
   Il testo è disteso e poi piegato sul tracciato: muovere le lettere in orizzontale equivale a farle camminare lungo la forma.
   Le distanze sono in lunghezze del testo (G.bw), così su un cerchio "1" è un giro intero. */
function walkFx(): EffectDef[] {
  const NOTE = ' Scegli prima una forma in "Testo su tracciato" (movimento continuo).';
  const from = sel('from', 'Provenienza', [['B', 'Da dietro'], ['F', 'Da davanti']], 'B');
  const sg = (o: any) => (o.from === 'F' ? 1 : -1);
  return [
    { id: 'walkin', n: 'Cammina', c: 'Su tracciato', d: 'Le lettere entrano camminando lungo il tracciato in fila, a partire dall\'ultima, e si fermano al loro posto. Se scegli "Da davanti" imposta l\'ordine su "Dall\'inizio".' + NOTE,
      rec: { split: 'char', stagger: .35, ease: 'outCubic', order: 'end' },
      p: [from, rng('D', 'Distanza', .1, 4, 1.2, .05, '× testo'), bool('fade', 'Dissolvenza', true)],
      f(s, p, u, o) { const q = 1 - p; s.x += sg(o) * o.D * G.bw * q; if (o.fade) s.op *= clamp(p * 3); } },
    { id: 'walkopen', n: 'Si apre sul tracciato', c: 'Su tracciato', d: 'Le lettere partono dallo stesso punto del tracciato e si distribuiscono camminando fino al loro posto.' + NOTE,
      rec: { split: 'char', stagger: .12, ease: 'outCubic', order: 'edges' },
      p: [sel('from', 'Punto di partenza', [['C', 'Centro'], ['L', 'Inizio'], ['R', 'Fine']], 'C'), bool('fade', 'Dissolvenza', true)],
      f(s, p, u, o) { const x0 = o.from === 'L' ? -G.bw / 2 : o.from === 'R' ? G.bw / 2 : 0; s.x += (x0 - u.cx) * (1 - p); if (o.fade) s.op *= clamp(p * 4); } },
    { id: 'walkroll', n: 'Rotola', c: 'Su tracciato', d: 'Le lettere arrivano rotolando lungo il tracciato, come ruote.' + NOTE,
      rec: { split: 'char', stagger: .35, ease: 'outCubic', order: 'end' },
      p: [from, rng('D', 'Distanza', .1, 4, 1, .05, '× testo'), rng('turns', 'Giri', 0, 6, 2, .25), bool('fade', 'Dissolvenza', true)],
      f(s, p, u, o) { const q = 1 - p; s.x += sg(o) * o.D * G.bw * q; s.rot += sg(o) * o.turns * 360 * q; if (o.fade) s.op *= clamp(p * 3); } },
    { id: 'walkhop', n: 'Salta lungo il tracciato', c: 'Su tracciato', d: 'Le lettere arrivano a saltelli lungo il tracciato.' + NOTE,
      rec: { split: 'char', stagger: .4, ease: 'linear', order: 'end' },
      p: [from, rng('D', 'Distanza', .1, 4, 1, .05, '× testo'), rng('hops', 'Salti', 1, 12, 4, 1), rng('h', 'Altezza', 0, 1.5, .5, .01, 'em'), bool('fade', 'Dissolvenza', true)],
      f(s, p, u, o) { const q = 1 - clamp(p), e = EZ.outCubic(clamp(p)); s.x += sg(o) * o.D * G.bw * (1 - e); s.y -= Math.abs(Math.sin(Math.PI * o.hops * (1 - e))) * o.h * G.E * q; if (o.fade) s.op *= clamp(p * 3); } },
  ];
}
